#if/else

#when - keyword 

- name: Demo on Conditions
  hosts: localhost
  tasks:
    - name: Vegetables
      ansible.builtin.debug:
        msg: vegetables
      when: type == "vegetables"

    - name: Fruits
      ansible.builtin.debug:
        msg: fruits
      when: type == "fruits"  

    - name: watches
      ansible.builtin.debug:
        msg: watches
      when: type == "watches" 

    - name: Laptops
      ansible.builtin.debug:
        msg: laptops
      when: type == "laptops" 